frase = input("\nDigite Algo: ")
print('\nO tipo primitivo deste valor é ', type(frase))
print('Só tem espaços? ', frase.isspace())
print('É um número? ', frase.isnumeric())
print('É alfabético? ', frase.isalpha())
print('É alfanumérico? ', frase.isalnum())
print('Está em maiúsculas? ', frase.isupper())
print('Está em minúsculas? ', frase.islower())
print('Está capitalizada? ', frase.istitle())
print('O tamanho da string é: ', len(frase),'\n')    