print ('-=' * 18)
print (' ' * 10 + 'Triangle Analyzer')
print ('-=' * 18)
print('\nInput the lengths of the three sides of a triangle:')
a = float(input('First side: '))
b = float(input('Second side: '))
c = float(input('Third side: '))
